### PR TITLE
Add github action to generate wiki from files

### PR DESCRIPTION
**Pull request by quellus**
This allows people to contribute to the wiki by editing the files in the `wiki` directory and opening a pull request.

### CODE REVIEW

**Comment by quellus** [comment]
@Thefunguy-Github is going to love this one

**Review by code807 — APPROVED** [review]

**Comment by dohro-github** [comment]
Yoooo

**Comment by dohro-github** [comment]
How do i use it?

**Comment by quellus** [comment]
@Thefunguy-Github  The wiki is now stored in the [wiki](https://github.com/quellus/GDTuber/tree/main/wiki) directory in the repo so you can edit the wiki by editing the files in that directory. Each file is a different wiki page.

While adding this change, we had to remove the setup page from the wiki, so you can add it back by creating a wiki/Setup.md file. Here was the contents that were in there:

```Download the latest release for your Operating System from https://github.com/quellus/GDTuber/releases
# Setup in OBS
1. Create a Game Capture source
2. Set Mode to "Capture specific window"
3. Set Window to the GDTuber window
4. Select Allow Transparency at the bottom
# Image Setup
If using the single-image avatar setting, one image must contain the separate avatar visual states either side by side and/or on the top and bottom halves of the image. If an avatar has a blinking animation, it should take up the bottom half of the image. If an avatar has a talking animation, it should take up the right half of the image.

**Pull request merged**
