### PR TITLE
Added timers to automatically toggle screen objects

### LINKED ISSUE #116: [Feature Request]: Timed effects
### Is your feature request related to a problem? Please describe.

set up timer to replace displayobject for N - Time

### Describe the solution you'd like

Create a tab for config to displayobjects settings 
settings:
> time 
>  object to replace 

Add an button to start replacing.

replacing:

>  hide selected object 
> show object this object

after timer is up, switch back to orginal state.

### Describe alternatives you've considered

_No response_

### Additional Context

Feel free to correct my grammar.

### PR DESCRIPTION
**Pull request by quellus**
There's now an option in the Screen Object settings to turn on the timer.
Enabling this option adds a ScreenObjectMenu button for the autotoggle.
Pressing the autotoggle will change the visibility for x amount of time.
image

Closes #116

### CODE REVIEW

**Comment by dohro-github** [comment]
cool

**Comment by dohro-github** [comment]
It was hard but you got there, gg

**Comment by quellus** [comment]
Fix the tooltips
Move the toggle to a different menu, maybe the animation menu
Rename the toggle button better
Change the icon to an hour glass or make the clock logo more obvious

**Review by code807 — APPROVED** [review]
Looks good!

**Pull request merged**
